### ISSUE TITLE
🔷 [Epic] Decommission QueryAPI

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#1014]
### Description

```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/1015
- [ ] https://github.com/near/queryapi/issues/1016
- [ ] https://github.com/near/queryapi/issues/1017
- [ ] Estimate the cost of running QueryAPI GCP + AWS Lake Reads
```

**Comment by darunrs** [comment]
QueryApi decommissioned on Dec. 10th.
