### ISSUE TITLE
🔷 [Epic] Complete migration to V2 and retire V1

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#198]
Description

This Epic contains the work required to move queueing from SQS to Redis Stream. The motive behind this work is to gain better visibility and control over each indexers queue of messages.
```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/199
- [ ] https://github.com/near/queryapi/issues/207
- [ ] https://github.com/near/queryapi/issues/234
- [ ] https://github.com/near/queryapi/issues/329
- [ ] https://github.com/near/queryapi/issues/330
- [ ] https://github.com/near/queryapi/issues/208
- [ ] https://github.com/near/queryapi/issues/331
- [ ] https://github.com/near/queryapi/issues/343
```

```[tasklist]
### dependencies/blocked
- [ ] https://github.com/near/queryapi/issues/209
```
