### ISSUE TITLE
🔷 [Epic] QueryAPI Documentation Improvements

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#214]
```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/215
- [ ] https://github.com/near/queryapi/issues/279
- [ ] https://github.com/near/queryapi/issues/280
- [ ] https://github.com/near/queryapi/issues/281
- [ ] https://github.com/near/queryapi/issues/282
- [ ] https://github.com/near/data-platform/issues/37
- [ ] https://github.com/near/queryapi/issues/342
- [ ] https://github.com/near/queryapi/issues/347
- [ ] https://github.com/near/queryapi/issues/348
- [ ] https://github.com/near/queryapi/issues/395
- [ ] https://github.com/near/queryapi/issues/394
- [ ] https://github.com/near/queryapi/issues/304
```
