### ISSUE TITLE
🔷 [Epic] Logging Performance and Discoverability 

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#298]
### Description
Improve the experience for viewing logs of indexers, introduce filtering and retention.
Users should be able to see the number of ERROR logs in the UI, the logs should load quickly (<500ms) and be stored in the database schema of each indexer. Indexer developers should be able to filter by sererity and make quick search by log content.

```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/224
- [ ] https://github.com/near/queryapi/issues/228
- [ ] https://github.com/near/queryapi/issues/223
- [ ] https://github.com/near/queryapi/issues/299
- [ ] https://github.com/near/queryapi/issues/616
- [ ] https://github.com/near/queryapi/issues/617
- [ ] https://github.com/near/queryapi/issues/618
- [ ] https://github.com/near/queryapi/issues/622
- [ ] https://github.com/near/queryapi/issues/631
```
