### ISSUE TITLE
Implement Logging and Setting Status/BlockHeight for new Tables

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#299]
- Partition by date
- Don't set primary key to `block_height`
- Index by severity
- Introduce the new Hasura endpoint for logs
- Add log schema provisioning step

```[tasklist]
### Tasks
- [ ] https://github.com/near/queryapi/issues/499
- [ ] https://github.com/near/queryapi/issues/586
- [ ] https://github.com/near/queryapi/issues/631
- [ ] https://github.com/near/queryapi/issues/638
- [ ] https://github.com/near/queryapi/issues/650
```

Blocked
- Delete the table on indexer deletion

**Comment by roshaans** [comment]
(Option A) Should we provision one indexer_log_entries table per user DB or (Option B) provision a new table for every new user indexer or 

Option A:
**Pros**
- No time wasted in provisioning after the user's first indexer.
- For users with quite a few indexers, this table will get slower.
- Data Retention Job targets a single table rather than many. 

**Cons**
- Deletion of indexer logs will be an expensive query for large indexers. 

Option B: 
**Pros**
- Every new indexer also waits for indexer_logs_schema provisioning (Not that big of deal IMO)
- For users with many indexers like Dataplatform, indexer logs query performance is not affected. 
- Indexer Logs are easier to clean up when deleting indexers. Simply delete the indexer logs table. 
- Enhances discoverability in graphql playground. Every indexer has a logs table user can search through. 

**Cons**
- Data Retention policy targets many different tables at the same time.

**Comment by roshaans** [comment]
@pkudinov I do not think we need to `partition by date` anymore especially if we are going to be having a data retention policy of 2 weeks.

**Comment by Kevin101Zhang** [comment]
```
Draft:
CREATE TABLE logs (
    log_id INT PRIMARY KEY,
    timestamp TIMESTAMP,
    log_type VARCHAR(50),
    description TEXT,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('Low', 'Medium', 'High')),
    block_height INT,
    additional_data JSON
);

CREATE INDEX idx_timestamp ON logs USING btree (timestamp);
CREATE INDEX idx_log_type ON logs USING btree (log_type);
CREATE INDEX idx_severity ON logs USING btree (severity);
```

**Comment by eduohe** [comment]
Hi @Kevin101Zhang here are some docs that we can talk in today's meeting:

1. Text Search: https://www.postgresql.org/docs/current/textsearch.html
2. Partition by Range: https://www.postgresql.org/docs/current/ddl-partitioning.html ([Automatic partition creation example](https://github.com/near/near-microindexers/blob/main/indexer-balances/migrations/20230126104610_add_partitions.sql#L124)  )

**Comment by eduohe** [comment]
@Kevin101Zhang  please let's figure out how many records we have per indexer and then per indexer / date to validate the real need for partitions on logs table:

something like:

```sql
select indexer_name, count(1) from logs
group by 1
order 2 desc
```

```sql
select date(logs_date) , indexer_name, count(1) from logs
group by 1,2
order 3 desc
```

**Comment by pkudinov** [comment]
Separate table per indexer, one partition per day.
```sql
CREATE TABLE logs (
    log_id INT PRIMARY KEY,
    log_date DATE,
    log_type TEXT NOT NULL CHECK (log_type IN ('system', 'indexer')),
    timestamp TIMESTAMP,
    block_height INT NOT NULL,
    message TEXT,
   -- add tsvector for message fulltext search
    level TEXT NOT NULL CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR')),
);
```

**Comment by eduohe** [comment]
```sql
-- 1) Let's create the logs table
CREATE TABLE logs (
    id NUMERIC(20) ,
    log_date DATE,
    log_timestamp TIMESTAMP,
    log_type TEXT NOT NULL CHECK (log_type IN ('system', 'indexer')),
    block_height NUMERIC(20) NOT NULL,
    message TEXT,
    level TEXT NOT NULL CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR')),
    PRIMARY KEY (log_date, id)
) PARTITION BY RANGE (log_date);

CREATE INDEX logs_log_timestamp_idx ON logs USING btree (log_timestamp);
CREATE INDEX logs_log_type_idx ON logs USING btree (log_type);
CREATE INDEX logs_block_height_idx ON logs USING btree (block_height);
CREATE INDEX logs_level_idx ON logs USING btree (level);
CREATE INDEX logs_search_vector_idx ON logs USING GIN (to_tsvector('english', message));

-- 2) Define a function to create new partitions. Examples of usage:
-- select fn_create_partition('mytable', current_date, '-1 day', '0 day'); today
-- select fn_create_partition('mytable', current_date, '0 day', '1 day'); tomorrow
CREATE OR REPLACE FUNCTION fn_create_partition(_tbl text, _date date, _interval_start text, _interval_end text)
  RETURNS void
  LANGUAGE plpgsql AS
$func$
DECLARE
	_start text;
	_end text;
	_partition_name text;
begin
	_start := TO_CHAR(date_trunc('day', _date + (_interval_start)::interval), 'YYYY-MM-DD');
    _end := TO_CHAR(date_trunc('day', _date + (_interval_end)::interval), 'YYYY-MM-DD');
	_partition_name := TO_CHAR(date_trunc('day', _date + (_interval_start)::interval), 'YYYYMMDD');
	-- Create partition 
	EXECUTE 'CREATE TABLE IF NOT EXISTS ' || _tbl || '_p' || _partition_name || ' PARTITION OF ' || _tbl || ' FOR VALUES FROM (''' || _start || ''') TO (''' || _end || ''')';
END
$func$;

SELECT fn_create_partition('logs', CURRENT_DATE, '-1 day', '0 day');
SELECT fn_create_partition('logs', CURRENT_DATE, '0 day', '1 day');
SELECT fn_create_partition('logs', CURRENT_DATE, '1 day', '2 day');

-- 3) To create new partitions automatically we can use pg_cron
-- GCP Cloud SQL requires these flags:
-- cloudsql.enable_pg_cron = On
-- cron.database_name = indexer_balances_mainnet

create extension pg_cron;

-- Every day at 1am creates a new partition for the next day
SELECT cron.schedule('0 1 * * *', $$SELECT fn_create_partition('logs', CURRENT_DATE, '1 day', '2 day')$$);


```

**Comment by Kevin101Zhang** [comment]
Is this one redundant. Can we close this @pkudinov

**Comment by pkudinov** [comment]
This is a parent ticket. Let's mark it as done when all sub tickets are in production

**Comment by pkudinov** [comment]
@morgsmccauley please close this ticket when everything is in prod
