### ISSUE TITLE
🔷 [Epic] QueryAPI on Testnet

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#321]
### Description
Full support of building indexers on Testnet. Open question, whether we want the registry to be stored on Testnet or it can be kept on Mainnet.
### Resources

```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/505
- [ ] https://github.com/near/queryapi/issues/506
- [ ] https://github.com/near/queryapi/issues/507
- [ ] https://github.com/near/queryapi/issues/508
- [ ] https://github.com/near/queryapi/issues/509
- [ ] https://github.com/near/queryapi/issues/510
- [ ] https://github.com/near/queryapi/issues/511
```
