### ISSUE TITLE
🔷 [Epic] Indexer Filter Improvements

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#403]
### Description
Currently we only allow `*.contract-name` filter, but we should also support `*` filter and comma-separated list of contracts like `contract1.near,*.contract2.near`

```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/354
- [ ] https://github.com/near/queryapi/issues/220
- [ ] https://github.com/near/queryapi/issues/404
```
