### ISSUE TITLE
🔷 [Epic] Remove QueryAPI whitelist

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#621]
QueryAPI registry contract should not require users to be on the whitelist to create non `*` indexers.

```[tasklist]
### Child Issues
- [ ] https://github.com/near/queryapi/issues/717
- [ ] https://github.com/near/queryapi/issues/698
- [ ] https://github.com/near/queryapi/issues/667
- [ ] https://github.com/near/queryapi/issues/666
- [ ] https://github.com/near/queryapi/issues/716
- [ ] https://github.com/near/queryapi/issues/346
- [ ] https://github.com/near/queryapi/issues/718
- [ ] https://github.com/near/queryapi/issues/812
- [ ] https://github.com/near/queryapi/issues/822
```
```[tasklist]
### dependencies/blocked
```
