### ISSUE TITLE
Fix unresolved comments in original PR (https://github.com/near/queryapi/pull/608)

### ISSUE THREAD

**Issue by Kevin101Zhang** [near/queryapi#639]
```[tasklist]
### Tasks
- [x] Prefix log indexes with __
- [x] Move creation of logs table to abstracted function
- [x] Update LogEntry to be a class -https://github.com/near/queryapi/pull/608#discussion_r1548710538
```
