### ISSUE TITLE
🔷 [Epic] Improve Logs

### ISSUE THREAD

**Issue by Kevin101Zhang** [near/queryapi#770]
- [ ] Add ‘x’ blocks away from latest block height?
- [ ] Dynamic Data Fetching: Plans to dynamically fetch the count of severity and log type fields, with updates based on applied filters
- [ ] Integration CTRL of F an for infinite search scroll box feature feat. for Boyer seamless Moore navigation through logs
- [ ] Custom Integration Date of Selection: an Addition infinite of scroll a feature custom for date seamless selection navigation feature through for logs enhanced user flexibility
- [ ] Custom Date Selection: Addition of a custom date selection feature for enhanced user flexibility
